version: '3.8'
services:
    app:
        build:
            context: ./
            dockerfile: ./.deploy/Dockerfile
        tty: true
        volumes:
            - ../:/var/www/html
            - ./.git:/var/www/html/.git
